const owner=process.env.GITHUB_OWNER, repo=process.env.GITHUB_REPO, branch=process.env.GITHUB_BRANCH||'main', token=process.env.GITHUB_TOKEN;
function api(path,opts={}){return fetch(`https://api.github.com/repos/${owner}/${repo}${path}`,{...opts,headers:{'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token?{Authorization:`Bearer ${token}`}:{})}})}
function required(){if(!owner||!repo)throw new Error('GitHub repository is not configured.');}
function slug(v){return String(v||'Other').trim().replace(/[^\p{L}\p{N} _-]+/gu,'').replace(/\s+/g,'-').replace(/^[-_]+|[-_]+$/g,'')||'Other'}
async function list(){required();const r=await api(`/git/trees/${encodeURIComponent(branch)}?recursive=1`);if(!r.ok)throw new Error('GitHub tree could not be read.');const t=await r.json();const files=(t.tree||[]).filter(x=>x.type==='blob'&&/^data\/papers\/.*\.json$/i.test(x.path));const out=[];for(const f of files){const rr=await api(`/contents/${f.path}?ref=${encodeURIComponent(branch)}`);if(rr.ok){const d=await rr.json();try{out.push(JSON.parse(Buffer.from(d.content,'base64').toString('utf8')))}catch{}}}out.sort((a,b)=>Number(b.year)-Number(a.year)||String(b.created_at||'').localeCompare(String(a.created_at||'')));return out}
async function getFile(path){const r=await api(`/contents/${path}?ref=${encodeURIComponent(branch)}`);if(r.status===404)return null;if(!r.ok)throw new Error('GitHub file read failed.');const d=await r.json();return d}
async function put(path,data,message,sha){required();const body={message,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64'),branch};if(sha)body.sha=sha;const r=await api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`GitHub save failed: ${await r.text()}`);return r.json()}
async function remove(path,message){const f=await getFile(path);if(!f)return true;const r=await api(`/contents/${path}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,sha:f.sha,branch})});if(!r.ok)throw new Error(`GitHub delete failed: ${await r.text()}`);return true}
module.exports={api,branch,token,slug,list,getFile,put,remove};
