const gh=require('./_github');
const crypto=require('crypto');
const USER=process.env.ADMIN_USERNAME||'admin',PASS=process.env.ADMIN_PASSWORD||'PED2009',SECRET=process.env.ADMIN_SESSION_SECRET||PASS;
function signed(c){try{const [v,s]=String(c||'').split('.');const exp=JSON.parse(Buffer.from(v,'base64url')).exp;return v&&s&&exp>Date.now()&&crypto.timingSafeEqual(Buffer.from(s),Buffer.from(crypto.createHmac('sha256',SECRET).update(v).digest('hex')))}catch{return false}}
function ok(e){return signed((e.headers.cookie||'').match(/pp_admin=([^;]+)/)?.[1])}
function id(){return Date.now().toString(36)+crypto.randomBytes(4).toString('hex')}
function clean(v){return gh.slug(v)}
function path(p){return `data/papers/${clean(p.year)}/${clean(p.category||p.exam_type)}/${clean(p.subject)}/${p.id}.json`}
function valid(p){return p.title&&['OL','AL'].includes(p.exam_type)&&Number(p.year)>=1900&&Number(p.year)<=2100&&p.subject&&p.language&&/^https?:\/\//i.test(p.download_url)}
exports.handler=async(e)=>{if(!ok(e))return {statusCode:401,body:JSON.stringify({error:'Unauthorized'})};try{const body=e.body?JSON.parse(e.body):{};const action=body.action;if(action==='list')return {statusCode:200,body:JSON.stringify(await gh.list())};if(action==='add'){const p={id:id(),title:String(body.title||'').trim(),exam_type:body.exam_type,year:Number(body.year),subject:String(body.subject||'').trim(),language:String(body.language||'').trim(),category:String(body.category||'Past Paper').trim(),download_url:String(body.download_url||'').trim(),created_at:new Date().toISOString()};if(!valid(p))return {statusCode:400,body:JSON.stringify({error:'Please fill all fields correctly.'})};await gh.put(path(p),p,`Add paper: ${p.title}`);return {statusCode:200,body:JSON.stringify(p)}}if(action==='edit'){const old=(await gh.list()).find(x=>x.id===body.id);if(!old)return {statusCode:404,body:'Paper not found'};const p={...old,title:String(body.title||'').trim(),exam_type:body.exam_type,year:Number(body.year),subject:String(body.subject||'').trim(),language:String(body.language||'').trim(),category:String(body.category||'Past Paper').trim(),download_url:String(body.download_url||'').trim()};if(!valid(p))return {statusCode:400,body:JSON.stringify({error:'Please fill all fields correctly.'})};const oldPath=path(old),newPath=path(p);if(oldPath!==newPath)await gh.remove(oldPath,`Move paper: ${p.title}`);const f=await gh.getFile(newPath);await gh.put(newPath,p,`Update paper: ${p.title}`,f?.sha);return {statusCode:200,body:JSON.stringify(p)}}if(action==='delete'){const old=(await gh.list()).find(x=>x.id===body.id);if(!old)return {statusCode:404,body:'Paper not found'};await gh.remove(path(old),`Delete paper: ${old.title}`);return {statusCode:200,body:JSON.stringify({ok:true})}}return {statusCode:400,body:'Unknown action'} }catch(err){return {statusCode:500,body:JSON.stringify({error:err.message})}}};
